on:
    schedule:
     - cron: '30 21,23 * * 1-5'
    workflow_dispatch:

name: Ballot Tracker 2024
  
jobs:
  render:
    name: Pull latest ballot return data and render it 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increase Git buffer size
        run: git config --global http.postBuffer 524288000
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("tidyverse","janitor", "readxl", "openxlsx", "XLConnect", "rmarkdown", "stringr","data.table"))'
      - name: Get ballot return data
        run: Rscript scripts/render-ballot-markdown.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Update returned ballots tracker' || echo "No changes"
          git push origin || echo "No changes to commit"
